### ISSUE TITLE
keep only binary field gcards for gemc >=5.3

### ISSUE THREAD

**Issue by raffaelladevita** [JeffersonLab/clas12-config#7]
The use of the binary-field map addresses the phi vs. z dependence observed with the ASCII maps, as shown in the plots below. According to previous studies, this was due to an inconsistency between the field in gemc and reconstruction in the solenoid-torus maps overlap region. As expected, this disappears when the binary map is used. 

Based on this, the gcards using the ASCII maps should be dropped from the gemc 5.3 folder.
For gemc 5.2 or before, the solenoid and torus scales were not saved in RUN::config when the binary map was selected. For those, only ASCII maps should be kept or maybe the whole directory gemc/5.X with X<=2, dropped.

![Plot_08-07-2023_11 20 50_AM](https://github.com/JeffersonLab/clas12-config/assets/7524926/414d24f3-7c4d-4f78-9b8f-7d2056a2c71d)
![Plot_08-07-2023_11 20 24_AM](https://github.com/JeffersonLab/clas12-config/assets/7524926/236325a5-5a4e-4ab3-a44b-b8450d5dd522)

**Comment by raffaelladevita** [comment]
For records, the simulations were done with 4 GeV muons at theta=20 deg, torus=-1 and solenoid=-2.
No idea of what is the wiggle in sector 3

**Comment by maureeungaro** [comment]
With 5.1 and 5.2 dropped, on the OSG we'd have:

- 4.4.2 with ASCII fields
- 5.3 (for testing) to be replaced by 5.4 ( be released once we're ready) with Binary fields.

**Comment by maureeungaro** [comment]
addressed in PR
