### ISSUE TITLE
pass1 vs. pass2 gcards

### ISSUE THREAD

**Issue by raffaelladevita** [JeffersonLab/clas12-config#8]
Since we have new run group variations for pass2 simulations, we should update the digitization variation in the gcards from 
rga_fall2018_bg (used for all data sets)
to
rga_spring2018_mc
rga_fall2018_mc (for RG-K too)
rga_spring2019_mc
rgb_spring2019_mc
rgb_fall2019_mc
rgm_fall2021_mc
rgc_summer2022_mc

If we want to keep using the old variation for pass1 simulations, we will need separate gcards

**Comment by maureeungaro** [comment]
This is addressed in https://github.com/gemc/clas12Tags , see below, and will be propagated to the next tags and to clas12-config, starting with 5.4. 

 
gcard name : DIGITIZATION_VARIATION 

<ul>
<li> rgk_fall2018_FTOff : rga_fall2018_mc </li> 
<li> rgf_spring2020 : rgf_spring2020_mc </li> 
<li> rgk_fall2018_FTOn : rga_fall2018_mc </li> 
<li> rgc_summer2022_FTOn : rgc_summer2022_mc </li> 
<li> rga_fall2018 : rga_fall2018_mc </li> 
<li> rga_spring2019 : rga_spring2019_mc </li> 
<li> rgb_spring2019 : rgb_spring2019_mc </li> 
<li> rga_spring2018 : rga_spring2018_mc </li> 
<li> rgc_summer2022_Elmo : rgc_summer2022_mc </li> 
<li> clas12-default : default </li> 
<li> rgb_fall2019 : rgb_fall2019_mc </li> 
 </ul>

**Comment by baltzell** [comment]
shall we remove pass# from the YAML names?  That would be better in a README probably?

**Comment by baltzell** [comment]
sounds like this was addressed?
